### ISSUE TITLE
Dm me on discord

### ISSUE THREAD

**Issue by Eruptsy** [Nexuzzzz/amyntas#10]
dm me on discord. i have a few question for ya

杰弗里#3281

discord server: https://discord.gg/TpNaJ2n6rx

**Comment by Nexuzzzz** [comment]
sorry, i don't accept skids

**Comment by Eruptsy** [comment]
Skid? do you not see your github 😂

**Comment by Nexuzzzz** [comment]
> Skid? do you not see your github joy

yet you came here to question me, the fuck do you want?

**Comment by Eruptsy** [comment]
Yes question you on why the fuck half the project has noob practices 😭😭😭😭

**Comment by Nexuzzzz** [comment]
if you don't like it, fuckoff

**Comment by Nexuzzzz** [comment]
also, i don't know why you say "noob practices" because your code uses elif chains that are 20 lines long, and you leave your API keys and webhooks vulnerable in the open.
