### ISSUE TITLE
Proxy list

### ISSUE THREAD

**Issue by ThomasCFelix** [Nexuzzzz/amyntas#3]
Add the feature to read proxies from text file

**Comment by Nexuzzzz** [comment]
> Add the feature to read proxies from text file

currently busy with exams, i'll see what i can do. I'll keep this open until i have added this

**Comment by Vermin-ux** [comment]
Hello Nexus it's Mr Vermin

**Comment by Vermin-ux** [comment]
A dangerous tool in vermins hands

**Comment by Vermin-ux** [comment]
Thanks for these brilliant tools :)

**Comment by Nexuzzzz** [comment]
> Thanks for these brilliant tools :)

cheers

**Comment by Vermin-ux** [comment]
【 i'm + not + a + hero + i'm + a + zero 】

**Comment by Vermin-ux** [comment]
【 i'm + not + a + hero + i'm + a + zero 】 
They all think I'm a bloody wiredo

**Comment by Nexuzzzz** [comment]
I've added the option, but it works with the `PROXY` flood only. Enjoy :P
